apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mydbsecret
  name: mydbsecret
spec:
  containers:
  - envFrom:
    - secretRef:
       name: shram
    image: mysql
    name: mydbsecret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

